### ISSUE TITLE
Local file reference

### ISSUE THREAD

**Issue by jssuttles** [WaleedAshraf/asyncapi-github-action#15]
How does this action handle local file references?
It seems to be starting at the root of the project instead of being relative to the schema file.

For example:

```
- project
  - schemas
    - base-schema.yaml
    - components
      -  token.yaml
```

if something like this is in base-schema.yaml
```
token:
      $ref: './compoents/token.yaml'
```

It seems like it's trying to resolve this as project/components/token.yaml instead of project/schemas/components/token.yaml.

**Comment by WaleedAshraf** [comment]
It should work now with v0.0.6

**Comment by jssuttles** [comment]
Looks very good, thanks!
