### ISSUE TITLE
Unable to use Avro Schema Parser

### ISSUE THREAD

**Issue by VaclavChalupa** [WaleedAshraf/asyncapi-github-action#20]
When using `schemaFormat: "application/vnd.apache.avro;version=1.9.0"`, it fails with `PARSERS[String(...)] is not a function` error. It should be related to this issue https://github.com/asyncapi/parser-js/issues/157

To be able to validate AsyncAPI with Avro schema references, the https://github.com/asyncapi/avro-schema-parser has to be registered:

```
const avroSchemaParser = require('@asyncapi/avro-schema-parser')
parser.registerSchemaParser(avroSchemaParser);
```

**Comment by WaleedAshraf** [comment]
@HEm3R I see. You may create a PR for the fix? Else, I'll release a new version by this weekend.

**Comment by VaclavChalupa** [comment]
@WaleedAshraf I will try it, not a js guy :)
