### ISSUE TITLE
Did you consider using latest parser to support AsyncAPI 2.6?

### ISSUE THREAD

**Issue by derberg** [WaleedAshraf/asyncapi-github-action#25]
Upgrading `@asyncapi/parser` to [1.18](https://github.com/asyncapi/parser-js/releases/tag/v1.18.1) will make this validation action support AsyncAPI 2.6

**Comment by WaleedAshraf** [comment]
I've released a new version. 
https://github.com/WaleedAshraf/asyncapi-github-action/releases/tag/v0.0.10
